//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.ParsianConfirmRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(API.ParsianConfirmRef.ClientConfirmWithAmountRequestData))]
    public partial class ClientConfirmRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAccountField;
        
        private long TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount {
            get {
                return this.LoginAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAccountField, value) != true)) {
                    this.LoginAccountField = value;
                    this.RaisePropertyChanged("LoginAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmWithAmountRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.SerializableAttribute()]
    public partial class ClientConfirmWithAmountRequestData : API.ParsianConfirmRef.ClientConfirmRequestData {
        
        private long OrderIdField;
        
        private long AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.SerializableAttribute()]
    public partial class ClientConfirmResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberMaskedField;
        
        private long RRNField;
        
        private long TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CardNumberMasked {
            get {
                return this.CardNumberMaskedField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberMaskedField, value) != true)) {
                    this.CardNumberMaskedField = value;
                    this.RaisePropertyChanged("CardNumberMasked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long RRN {
            get {
                return this.RRNField;
            }
            set {
                if ((this.RRNField.Equals(value) != true)) {
                    this.RRNField = value;
                    this.RaisePropertyChanged("RRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", ConfigurationName="ParsianConfirmRef.ConfirmServiceSoap")]
    public interface ConfirmServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPayment", ReplyAction="*")]
        API.ParsianConfirmRef.ConfirmPaymentResponse ConfirmPayment(API.ParsianConfirmRef.ConfirmPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<API.ParsianConfirmRef.ConfirmPaymentResponse> ConfirmPaymentAsync(API.ParsianConfirmRef.ConfirmPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "mount", ReplyAction="*")]
        API.ParsianConfirmRef.ConfirmPaymentWithAmountResponse ConfirmPaymentWithAmount(API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "mount", ReplyAction="*")]
        System.Threading.Tasks.Task<API.ParsianConfirmRef.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPayment", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public API.ParsianConfirmRef.ConfirmPaymentRequestBody Body;
        
        public ConfirmPaymentRequest() {
        }
        
        public ConfirmPaymentRequest(API.ParsianConfirmRef.ConfirmPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public API.ParsianConfirmRef.ClientConfirmRequestData requestData;
        
        public ConfirmPaymentRequestBody() {
        }
        
        public ConfirmPaymentRequestBody(API.ParsianConfirmRef.ClientConfirmRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public API.ParsianConfirmRef.ConfirmPaymentResponseBody Body;
        
        public ConfirmPaymentResponse() {
        }
        
        public ConfirmPaymentResponse(API.ParsianConfirmRef.ConfirmPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public API.ParsianConfirmRef.ClientConfirmResponseData ConfirmPaymentResult;
        
        public ConfirmPaymentResponseBody() {
        }
        
        public ConfirmPaymentResponseBody(API.ParsianConfirmRef.ClientConfirmResponseData ConfirmPaymentResult) {
            this.ConfirmPaymentResult = ConfirmPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmount", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public API.ParsianConfirmRef.ConfirmPaymentWithAmountRequestBody Body;
        
        public ConfirmPaymentWithAmountRequest() {
        }
        
        public ConfirmPaymentWithAmountRequest(API.ParsianConfirmRef.ConfirmPaymentWithAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public API.ParsianConfirmRef.ClientConfirmWithAmountRequestData requestData;
        
        public ConfirmPaymentWithAmountRequestBody() {
        }
        
        public ConfirmPaymentWithAmountRequestBody(API.ParsianConfirmRef.ClientConfirmWithAmountRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmountResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public API.ParsianConfirmRef.ConfirmPaymentWithAmountResponseBody Body;
        
        public ConfirmPaymentWithAmountResponse() {
        }
        
        public ConfirmPaymentWithAmountResponse(API.ParsianConfirmRef.ConfirmPaymentWithAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public API.ParsianConfirmRef.ClientConfirmResponseData ConfirmPaymentWithAmountResult;
        
        public ConfirmPaymentWithAmountResponseBody() {
        }
        
        public ConfirmPaymentWithAmountResponseBody(API.ParsianConfirmRef.ClientConfirmResponseData ConfirmPaymentWithAmountResult) {
            this.ConfirmPaymentWithAmountResult = ConfirmPaymentWithAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfirmServiceSoapChannel : API.ParsianConfirmRef.ConfirmServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfirmServiceSoapClient : System.ServiceModel.ClientBase<API.ParsianConfirmRef.ConfirmServiceSoap>, API.ParsianConfirmRef.ConfirmServiceSoap {
        
        public ConfirmServiceSoapClient() {
        }
        
        public ConfirmServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfirmServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.ParsianConfirmRef.ConfirmPaymentResponse API.ParsianConfirmRef.ConfirmServiceSoap.ConfirmPayment(API.ParsianConfirmRef.ConfirmPaymentRequest request) {
            return base.Channel.ConfirmPayment(request);
        }
        
        public API.ParsianConfirmRef.ClientConfirmResponseData ConfirmPayment(API.ParsianConfirmRef.ClientConfirmRequestData requestData) {
            API.ParsianConfirmRef.ConfirmPaymentRequest inValue = new API.ParsianConfirmRef.ConfirmPaymentRequest();
            inValue.Body = new API.ParsianConfirmRef.ConfirmPaymentRequestBody();
            inValue.Body.requestData = requestData;
            API.ParsianConfirmRef.ConfirmPaymentResponse retVal = ((API.ParsianConfirmRef.ConfirmServiceSoap)(this)).ConfirmPayment(inValue);
            return retVal.Body.ConfirmPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<API.ParsianConfirmRef.ConfirmPaymentResponse> API.ParsianConfirmRef.ConfirmServiceSoap.ConfirmPaymentAsync(API.ParsianConfirmRef.ConfirmPaymentRequest request) {
            return base.Channel.ConfirmPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<API.ParsianConfirmRef.ConfirmPaymentResponse> ConfirmPaymentAsync(API.ParsianConfirmRef.ClientConfirmRequestData requestData) {
            API.ParsianConfirmRef.ConfirmPaymentRequest inValue = new API.ParsianConfirmRef.ConfirmPaymentRequest();
            inValue.Body = new API.ParsianConfirmRef.ConfirmPaymentRequestBody();
            inValue.Body.requestData = requestData;
            return ((API.ParsianConfirmRef.ConfirmServiceSoap)(this)).ConfirmPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.ParsianConfirmRef.ConfirmPaymentWithAmountResponse API.ParsianConfirmRef.ConfirmServiceSoap.ConfirmPaymentWithAmount(API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest request) {
            return base.Channel.ConfirmPaymentWithAmount(request);
        }
        
        public API.ParsianConfirmRef.ClientConfirmResponseData ConfirmPaymentWithAmount(API.ParsianConfirmRef.ClientConfirmWithAmountRequestData requestData) {
            API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest inValue = new API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest();
            inValue.Body = new API.ParsianConfirmRef.ConfirmPaymentWithAmountRequestBody();
            inValue.Body.requestData = requestData;
            API.ParsianConfirmRef.ConfirmPaymentWithAmountResponse retVal = ((API.ParsianConfirmRef.ConfirmServiceSoap)(this)).ConfirmPaymentWithAmount(inValue);
            return retVal.Body.ConfirmPaymentWithAmountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<API.ParsianConfirmRef.ConfirmPaymentWithAmountResponse> API.ParsianConfirmRef.ConfirmServiceSoap.ConfirmPaymentWithAmountAsync(API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest request) {
            return base.Channel.ConfirmPaymentWithAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<API.ParsianConfirmRef.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(API.ParsianConfirmRef.ClientConfirmWithAmountRequestData requestData) {
            API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest inValue = new API.ParsianConfirmRef.ConfirmPaymentWithAmountRequest();
            inValue.Body = new API.ParsianConfirmRef.ConfirmPaymentWithAmountRequestBody();
            inValue.Body.requestData = requestData;
            return ((API.ParsianConfirmRef.ConfirmServiceSoap)(this)).ConfirmPaymentWithAmountAsync(inValue);
        }
    }
}
