//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedRole
    {
        public int AssignedRoleID { get; set; }
        public string AssignedRole1 { get; set; }
        public string PreferredTerm { get; set; }
        public string SpecificCategory { get; set; }
        public string Category1Tags { get; set; }
        public string OnetSocCode { get; set; }
        public string SocDetailedCode { get; set; }
        public Nullable<int> SumJobTitleUsageCount { get; set; }
        public Nullable<int> SumScore { get; set; }
        public string PublicKeywords { get; set; }
        public string SearchKeywords { get; set; }
        public string HumanSearchKeywords { get; set; }
        public string IndividualSearchWords { get; set; }
        public string CommonSearches { get; set; }
        public string IndeedSearch { get; set; }
        public string LinkedInSearches { get; set; }
        public string SimplyHiredSearches { get; set; }
        public string LinkUpSearches { get; set; }
        public string SalaryWebPage { get; set; }
        public string AssignedRoleStatus { get; set; }
        public string AssignedRoleStatusComment { get; set; }
    }
}
