//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public string Twitter { get; set; }
        public string LinkedIn { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> PersonId { get; set; }
        public System.DateTime DateJoin { get; set; }
        public string ZIPCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Network { get; set; }
        public string UserId { get; set; }
        public string Remark { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string NID { get; set; }
    }
}
