//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Review()
        {
            this.UserContentActivities = new HashSet<UserContentActivity>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Body { get; set; }
        public string Title { get; set; }
        public decimal TotalRate { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> DateConfirm { get; set; }
        public Nullable<int> ToPersonId { get; set; }
        public Nullable<int> ToPostId { get; set; }
        public Nullable<int> ToNetworkGroupId { get; set; }
        public Nullable<int> ToReviewId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserContentActivity> UserContentActivities { get; set; }
        public virtual Person Person { get; set; }
    }
}
