//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContentActivity
    {
        public int Id { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public string Remark { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual Person Person { get; set; }
    }
}
